/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as AccessRouteImport } from './routes/access'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TabsAttendanceRouteImport } from './routes/_tabs.attendance'
import { Route as TabsCameraRouteImport } from './routes/_tabs.camera'
import { Route as TabsCaptureRouteImport } from './routes/_tabs.capture'
import { Route as TabsCertificationsRouteImport } from './routes/_tabs.certifications'
import { Route as TabsChatRouteImport } from './routes/_tabs.chat'
import { Route as TabsComposeRouteImport } from './routes/_tabs.compose'
import { Route as TabsEditProfileRouteImport } from './routes/_tabs.edit-profile'
import { Route as TabsHelpRouteImport } from './routes/_tabs.help'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsIncidentNewRouteImport } from './routes/_tabs.incident-new'
import { Route as TabsIncidentsRouteImport } from './routes/_tabs.incidents'
import { Route as TabsNotificationsRouteImport } from './routes/_tabs.notifications'
import { Route as TabsPhotosRouteImport } from './routes/_tabs.photos'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsScheduleRouteImport } from './routes/_tabs.schedule'
import { Route as TabsSettingsRouteImport } from './routes/_tabs.settings'
import { Route as TabsSitesRouteImport } from './routes/_tabs.sites'
import { Route as TabsTasksRouteImport } from './routes/_tabs.tasks'
import { Route as TabsWaterHistoryRouteImport } from './routes/_tabs.water-history'
import { Route as TabsWaterTestRouteImport } from './routes/_tabs.water-test'
import { Route as TabsIncidentIncidentIdRouteImport } from './routes/_tabs.incident.$incidentId'
import { Route as TabsSiteSiteIdRouteImport } from './routes/_tabs.site.$siteId'
import { Route as TabsTaskTaskIdRouteImport } from './routes/_tabs.task.$taskId'
import { Route as TabsThreadThreadIdRouteImport } from './routes/_tabs.thread.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsAttendanceRoute = TabsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCameraRoute = TabsCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCaptureRoute = TabsCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCertificationsRoute = TabsCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChatRoute = TabsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => TabsRoute,
} as any)
const TabsComposeRoute = TabsComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => TabsRoute,
} as any)
const TabsEditProfileRoute = TabsEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHelpRoute = TabsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsIncidentNewRoute = TabsIncidentNewRouteImport.update({
  id: '/incident-new',
  path: '/incident-new',
  getParentRoute: () => TabsRoute,
} as any)
const TabsIncidentsRoute = TabsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => TabsRoute,
} as any)
const TabsNotificationsRoute = TabsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPhotosRoute = TabsPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsScheduleRoute = TabsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSettingsRoute = TabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSitesRoute = TabsSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => TabsRoute,
} as any)
const TabsTasksRoute = TabsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => TabsRoute,
} as any)
const TabsWaterHistoryRoute = TabsWaterHistoryRouteImport.update({
  id: '/water-history',
  path: '/water-history',
  getParentRoute: () => TabsRoute,
} as any)
const TabsWaterTestRoute = TabsWaterTestRouteImport.update({
  id: '/water-test',
  path: '/water-test',
  getParentRoute: () => TabsRoute,
} as any)
const TabsIncidentIncidentIdRoute = TabsIncidentIncidentIdRouteImport.update({
  id: '/incident/$incidentId',
  path: '/incident/$incidentId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSiteSiteIdRoute = TabsSiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsTaskTaskIdRoute = TabsTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsThreadThreadIdRoute = TabsThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/attendance': typeof TabsAttendanceRoute
  '/camera': typeof TabsCameraRoute
  '/capture': typeof TabsCaptureRoute
  '/certifications': typeof TabsCertificationsRoute
  '/chat': typeof TabsChatRoute
  '/compose': typeof TabsComposeRoute
  '/edit-profile': typeof TabsEditProfileRoute
  '/help': typeof TabsHelpRoute
  '/home': typeof TabsHomeRoute
  '/incident-new': typeof TabsIncidentNewRoute
  '/incidents': typeof TabsIncidentsRoute
  '/notifications': typeof TabsNotificationsRoute
  '/photos': typeof TabsPhotosRoute
  '/profile': typeof TabsProfileRoute
  '/schedule': typeof TabsScheduleRoute
  '/settings': typeof TabsSettingsRoute
  '/sites': typeof TabsSitesRoute
  '/tasks': typeof TabsTasksRoute
  '/water-history': typeof TabsWaterHistoryRoute
  '/water-test': typeof TabsWaterTestRoute
  '/incident/$incidentId': typeof TabsIncidentIncidentIdRoute
  '/site/$siteId': typeof TabsSiteSiteIdRoute
  '/task/$taskId': typeof TabsTaskTaskIdRoute
  '/thread/$threadId': typeof TabsThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/attendance': typeof TabsAttendanceRoute
  '/camera': typeof TabsCameraRoute
  '/capture': typeof TabsCaptureRoute
  '/certifications': typeof TabsCertificationsRoute
  '/chat': typeof TabsChatRoute
  '/compose': typeof TabsComposeRoute
  '/edit-profile': typeof TabsEditProfileRoute
  '/help': typeof TabsHelpRoute
  '/home': typeof TabsHomeRoute
  '/incident-new': typeof TabsIncidentNewRoute
  '/incidents': typeof TabsIncidentsRoute
  '/notifications': typeof TabsNotificationsRoute
  '/photos': typeof TabsPhotosRoute
  '/profile': typeof TabsProfileRoute
  '/schedule': typeof TabsScheduleRoute
  '/settings': typeof TabsSettingsRoute
  '/sites': typeof TabsSitesRoute
  '/tasks': typeof TabsTasksRoute
  '/water-history': typeof TabsWaterHistoryRoute
  '/water-test': typeof TabsWaterTestRoute
  '/incident/$incidentId': typeof TabsIncidentIncidentIdRoute
  '/site/$siteId': typeof TabsSiteSiteIdRoute
  '/task/$taskId': typeof TabsTaskTaskIdRoute
  '/thread/$threadId': typeof TabsThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_tabs/attendance': typeof TabsAttendanceRoute
  '/_tabs/camera': typeof TabsCameraRoute
  '/_tabs/capture': typeof TabsCaptureRoute
  '/_tabs/certifications': typeof TabsCertificationsRoute
  '/_tabs/chat': typeof TabsChatRoute
  '/_tabs/compose': typeof TabsComposeRoute
  '/_tabs/edit-profile': typeof TabsEditProfileRoute
  '/_tabs/help': typeof TabsHelpRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/incident-new': typeof TabsIncidentNewRoute
  '/_tabs/incidents': typeof TabsIncidentsRoute
  '/_tabs/notifications': typeof TabsNotificationsRoute
  '/_tabs/photos': typeof TabsPhotosRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/schedule': typeof TabsScheduleRoute
  '/_tabs/settings': typeof TabsSettingsRoute
  '/_tabs/sites': typeof TabsSitesRoute
  '/_tabs/tasks': typeof TabsTasksRoute
  '/_tabs/water-history': typeof TabsWaterHistoryRoute
  '/_tabs/water-test': typeof TabsWaterTestRoute
  '/_tabs/incident/$incidentId': typeof TabsIncidentIncidentIdRoute
  '/_tabs/site/$siteId': typeof TabsSiteSiteIdRoute
  '/_tabs/task/$taskId': typeof TabsTaskTaskIdRoute
  '/_tabs/thread/$threadId': typeof TabsThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/attendance'
    | '/camera'
    | '/capture'
    | '/certifications'
    | '/chat'
    | '/compose'
    | '/edit-profile'
    | '/help'
    | '/home'
    | '/incident-new'
    | '/incidents'
    | '/notifications'
    | '/photos'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/sites'
    | '/tasks'
    | '/water-history'
    | '/water-test'
    | '/incident/$incidentId'
    | '/site/$siteId'
    | '/task/$taskId'
    | '/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/attendance'
    | '/camera'
    | '/capture'
    | '/certifications'
    | '/chat'
    | '/compose'
    | '/edit-profile'
    | '/help'
    | '/home'
    | '/incident-new'
    | '/incidents'
    | '/notifications'
    | '/photos'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/sites'
    | '/tasks'
    | '/water-history'
    | '/water-test'
    | '/incident/$incidentId'
    | '/site/$siteId'
    | '/task/$taskId'
    | '/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/_tabs/attendance'
    | '/_tabs/camera'
    | '/_tabs/capture'
    | '/_tabs/certifications'
    | '/_tabs/chat'
    | '/_tabs/compose'
    | '/_tabs/edit-profile'
    | '/_tabs/help'
    | '/_tabs/home'
    | '/_tabs/incident-new'
    | '/_tabs/incidents'
    | '/_tabs/notifications'
    | '/_tabs/photos'
    | '/_tabs/profile'
    | '/_tabs/schedule'
    | '/_tabs/settings'
    | '/_tabs/sites'
    | '/_tabs/tasks'
    | '/_tabs/water-history'
    | '/_tabs/water-test'
    | '/_tabs/incident/$incidentId'
    | '/_tabs/site/$siteId'
    | '/_tabs/task/$taskId'
    | '/_tabs/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AccessRoute: typeof AccessRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/attendance': {
      id: '/_tabs/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof TabsAttendanceRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/camera': {
      id: '/_tabs/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof TabsCameraRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/capture': {
      id: '/_tabs/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof TabsCaptureRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/certifications': {
      id: '/_tabs/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof TabsCertificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/chat': {
      id: '/_tabs/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof TabsChatRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/compose': {
      id: '/_tabs/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof TabsComposeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/edit-profile': {
      id: '/_tabs/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof TabsEditProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/help': {
      id: '/_tabs/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof TabsHelpRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/incident-new': {
      id: '/_tabs/incident-new'
      path: '/incident-new'
      fullPath: '/incident-new'
      preLoaderRoute: typeof TabsIncidentNewRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/incidents': {
      id: '/_tabs/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof TabsIncidentsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/notifications': {
      id: '/_tabs/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof TabsNotificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/photos': {
      id: '/_tabs/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof TabsPhotosRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/schedule': {
      id: '/_tabs/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof TabsScheduleRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/settings': {
      id: '/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TabsSettingsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/sites': {
      id: '/_tabs/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof TabsSitesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/tasks': {
      id: '/_tabs/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TabsTasksRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/water-history': {
      id: '/_tabs/water-history'
      path: '/water-history'
      fullPath: '/water-history'
      preLoaderRoute: typeof TabsWaterHistoryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/water-test': {
      id: '/_tabs/water-test'
      path: '/water-test'
      fullPath: '/water-test'
      preLoaderRoute: typeof TabsWaterTestRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/incident/$incidentId': {
      id: '/_tabs/incident/$incidentId'
      path: '/incident/$incidentId'
      fullPath: '/incident/$incidentId'
      preLoaderRoute: typeof TabsIncidentIncidentIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/site/$siteId': {
      id: '/_tabs/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof TabsSiteSiteIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/task/$taskId': {
      id: '/_tabs/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TabsTaskTaskIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/thread/$threadId': {
      id: '/_tabs/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof TabsThreadThreadIdRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAttendanceRoute: typeof TabsAttendanceRoute
  TabsCameraRoute: typeof TabsCameraRoute
  TabsCaptureRoute: typeof TabsCaptureRoute
  TabsCertificationsRoute: typeof TabsCertificationsRoute
  TabsChatRoute: typeof TabsChatRoute
  TabsComposeRoute: typeof TabsComposeRoute
  TabsEditProfileRoute: typeof TabsEditProfileRoute
  TabsHelpRoute: typeof TabsHelpRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsIncidentNewRoute: typeof TabsIncidentNewRoute
  TabsIncidentsRoute: typeof TabsIncidentsRoute
  TabsNotificationsRoute: typeof TabsNotificationsRoute
  TabsPhotosRoute: typeof TabsPhotosRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsScheduleRoute: typeof TabsScheduleRoute
  TabsSettingsRoute: typeof TabsSettingsRoute
  TabsSitesRoute: typeof TabsSitesRoute
  TabsTasksRoute: typeof TabsTasksRoute
  TabsWaterHistoryRoute: typeof TabsWaterHistoryRoute
  TabsWaterTestRoute: typeof TabsWaterTestRoute
  TabsIncidentIncidentIdRoute: typeof TabsIncidentIncidentIdRoute
  TabsSiteSiteIdRoute: typeof TabsSiteSiteIdRoute
  TabsTaskTaskIdRoute: typeof TabsTaskTaskIdRoute
  TabsThreadThreadIdRoute: typeof TabsThreadThreadIdRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAttendanceRoute: TabsAttendanceRoute,
  TabsCameraRoute: TabsCameraRoute,
  TabsCaptureRoute: TabsCaptureRoute,
  TabsCertificationsRoute: TabsCertificationsRoute,
  TabsChatRoute: TabsChatRoute,
  TabsComposeRoute: TabsComposeRoute,
  TabsEditProfileRoute: TabsEditProfileRoute,
  TabsHelpRoute: TabsHelpRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsIncidentNewRoute: TabsIncidentNewRoute,
  TabsIncidentsRoute: TabsIncidentsRoute,
  TabsNotificationsRoute: TabsNotificationsRoute,
  TabsPhotosRoute: TabsPhotosRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsScheduleRoute: TabsScheduleRoute,
  TabsSettingsRoute: TabsSettingsRoute,
  TabsSitesRoute: TabsSitesRoute,
  TabsTasksRoute: TabsTasksRoute,
  TabsWaterHistoryRoute: TabsWaterHistoryRoute,
  TabsWaterTestRoute: TabsWaterTestRoute,
  TabsIncidentIncidentIdRoute: TabsIncidentIncidentIdRoute,
  TabsSiteSiteIdRoute: TabsSiteSiteIdRoute,
  TabsTaskTaskIdRoute: TabsTaskTaskIdRoute,
  TabsThreadThreadIdRoute: TabsThreadThreadIdRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AccessRoute: AccessRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
