/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as AccessRouteImport } from './routes/access'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TabsChangePasswordRouteImport } from './routes/_tabs.change-password'
import { Route as TabsEditProfileRouteImport } from './routes/_tabs.edit-profile'
import { Route as TabsHelpRouteImport } from './routes/_tabs.help'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsInspectionHistoryRouteImport } from './routes/_tabs.inspection-history'
import { Route as TabsInspectionsRouteImport } from './routes/_tabs.inspections'
import { Route as TabsMessagesRouteImport } from './routes/_tabs.messages'
import { Route as TabsNotificationsRouteImport } from './routes/_tabs.notifications'
import { Route as TabsPhotosRouteImport } from './routes/_tabs.photos'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsPropertiesRouteImport } from './routes/_tabs.properties'
import { Route as TabsPropertyNewRouteImport } from './routes/_tabs.property-new'
import { Route as TabsReportsRouteImport } from './routes/_tabs.reports'
import { Route as TabsRequestNewRouteImport } from './routes/_tabs.request-new'
import { Route as TabsRequestsRouteImport } from './routes/_tabs.requests'
import { Route as TabsSettingsRouteImport } from './routes/_tabs.settings'
import { Route as TabsAmenityAmenityIdRouteImport } from './routes/_tabs.amenity.$amenityId'
import { Route as TabsInspectionInspectionIdRouteImport } from './routes/_tabs.inspection.$inspectionId'
import { Route as TabsIssueIssueIdRouteImport } from './routes/_tabs.issue.$issueId'
import { Route as TabsPropertyPropertyIdRouteImport } from './routes/_tabs.property.$propertyId'
import { Route as TabsRequestRequestIdRouteImport } from './routes/_tabs.request.$requestId'
import { Route as TabsThreadThreadIdRouteImport } from './routes/_tabs.thread.$threadId'
import { Route as TabsWorkOrderWorkOrderIdRouteImport } from './routes/_tabs.work-order.$workOrderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsChangePasswordRoute = TabsChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => TabsRoute,
} as any)
const TabsEditProfileRoute = TabsEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHelpRoute = TabsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInspectionHistoryRoute = TabsInspectionHistoryRouteImport.update({
  id: '/inspection-history',
  path: '/inspection-history',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInspectionsRoute = TabsInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMessagesRoute = TabsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TabsRoute,
} as any)
const TabsNotificationsRoute = TabsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPhotosRoute = TabsPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPropertiesRoute = TabsPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPropertyNewRoute = TabsPropertyNewRouteImport.update({
  id: '/property-new',
  path: '/property-new',
  getParentRoute: () => TabsRoute,
} as any)
const TabsReportsRoute = TabsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRequestNewRoute = TabsRequestNewRouteImport.update({
  id: '/request-new',
  path: '/request-new',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRequestsRoute = TabsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSettingsRoute = TabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAmenityAmenityIdRoute = TabsAmenityAmenityIdRouteImport.update({
  id: '/amenity/$amenityId',
  path: '/amenity/$amenityId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInspectionInspectionIdRoute =
  TabsInspectionInspectionIdRouteImport.update({
    id: '/inspection/$inspectionId',
    path: '/inspection/$inspectionId',
    getParentRoute: () => TabsRoute,
  } as any)
const TabsIssueIssueIdRoute = TabsIssueIssueIdRouteImport.update({
  id: '/issue/$issueId',
  path: '/issue/$issueId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPropertyPropertyIdRoute = TabsPropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRequestRequestIdRoute = TabsRequestRequestIdRouteImport.update({
  id: '/request/$requestId',
  path: '/request/$requestId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsThreadThreadIdRoute = TabsThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsWorkOrderWorkOrderIdRoute =
  TabsWorkOrderWorkOrderIdRouteImport.update({
    id: '/work-order/$workOrderId',
    path: '/work-order/$workOrderId',
    getParentRoute: () => TabsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/change-password': typeof TabsChangePasswordRoute
  '/edit-profile': typeof TabsEditProfileRoute
  '/help': typeof TabsHelpRoute
  '/home': typeof TabsHomeRoute
  '/inspection-history': typeof TabsInspectionHistoryRoute
  '/inspections': typeof TabsInspectionsRoute
  '/messages': typeof TabsMessagesRoute
  '/notifications': typeof TabsNotificationsRoute
  '/photos': typeof TabsPhotosRoute
  '/profile': typeof TabsProfileRoute
  '/properties': typeof TabsPropertiesRoute
  '/property-new': typeof TabsPropertyNewRoute
  '/reports': typeof TabsReportsRoute
  '/request-new': typeof TabsRequestNewRoute
  '/requests': typeof TabsRequestsRoute
  '/settings': typeof TabsSettingsRoute
  '/amenity/$amenityId': typeof TabsAmenityAmenityIdRoute
  '/inspection/$inspectionId': typeof TabsInspectionInspectionIdRoute
  '/issue/$issueId': typeof TabsIssueIssueIdRoute
  '/property/$propertyId': typeof TabsPropertyPropertyIdRoute
  '/request/$requestId': typeof TabsRequestRequestIdRoute
  '/thread/$threadId': typeof TabsThreadThreadIdRoute
  '/work-order/$workOrderId': typeof TabsWorkOrderWorkOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/change-password': typeof TabsChangePasswordRoute
  '/edit-profile': typeof TabsEditProfileRoute
  '/help': typeof TabsHelpRoute
  '/home': typeof TabsHomeRoute
  '/inspection-history': typeof TabsInspectionHistoryRoute
  '/inspections': typeof TabsInspectionsRoute
  '/messages': typeof TabsMessagesRoute
  '/notifications': typeof TabsNotificationsRoute
  '/photos': typeof TabsPhotosRoute
  '/profile': typeof TabsProfileRoute
  '/properties': typeof TabsPropertiesRoute
  '/property-new': typeof TabsPropertyNewRoute
  '/reports': typeof TabsReportsRoute
  '/request-new': typeof TabsRequestNewRoute
  '/requests': typeof TabsRequestsRoute
  '/settings': typeof TabsSettingsRoute
  '/amenity/$amenityId': typeof TabsAmenityAmenityIdRoute
  '/inspection/$inspectionId': typeof TabsInspectionInspectionIdRoute
  '/issue/$issueId': typeof TabsIssueIssueIdRoute
  '/property/$propertyId': typeof TabsPropertyPropertyIdRoute
  '/request/$requestId': typeof TabsRequestRequestIdRoute
  '/thread/$threadId': typeof TabsThreadThreadIdRoute
  '/work-order/$workOrderId': typeof TabsWorkOrderWorkOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/access': typeof AccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_tabs/change-password': typeof TabsChangePasswordRoute
  '/_tabs/edit-profile': typeof TabsEditProfileRoute
  '/_tabs/help': typeof TabsHelpRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/inspection-history': typeof TabsInspectionHistoryRoute
  '/_tabs/inspections': typeof TabsInspectionsRoute
  '/_tabs/messages': typeof TabsMessagesRoute
  '/_tabs/notifications': typeof TabsNotificationsRoute
  '/_tabs/photos': typeof TabsPhotosRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/properties': typeof TabsPropertiesRoute
  '/_tabs/property-new': typeof TabsPropertyNewRoute
  '/_tabs/reports': typeof TabsReportsRoute
  '/_tabs/request-new': typeof TabsRequestNewRoute
  '/_tabs/requests': typeof TabsRequestsRoute
  '/_tabs/settings': typeof TabsSettingsRoute
  '/_tabs/amenity/$amenityId': typeof TabsAmenityAmenityIdRoute
  '/_tabs/inspection/$inspectionId': typeof TabsInspectionInspectionIdRoute
  '/_tabs/issue/$issueId': typeof TabsIssueIssueIdRoute
  '/_tabs/property/$propertyId': typeof TabsPropertyPropertyIdRoute
  '/_tabs/request/$requestId': typeof TabsRequestRequestIdRoute
  '/_tabs/thread/$threadId': typeof TabsThreadThreadIdRoute
  '/_tabs/work-order/$workOrderId': typeof TabsWorkOrderWorkOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/change-password'
    | '/edit-profile'
    | '/help'
    | '/home'
    | '/inspection-history'
    | '/inspections'
    | '/messages'
    | '/notifications'
    | '/photos'
    | '/profile'
    | '/properties'
    | '/property-new'
    | '/reports'
    | '/request-new'
    | '/requests'
    | '/settings'
    | '/amenity/$amenityId'
    | '/inspection/$inspectionId'
    | '/issue/$issueId'
    | '/property/$propertyId'
    | '/request/$requestId'
    | '/thread/$threadId'
    | '/work-order/$workOrderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/change-password'
    | '/edit-profile'
    | '/help'
    | '/home'
    | '/inspection-history'
    | '/inspections'
    | '/messages'
    | '/notifications'
    | '/photos'
    | '/profile'
    | '/properties'
    | '/property-new'
    | '/reports'
    | '/request-new'
    | '/requests'
    | '/settings'
    | '/amenity/$amenityId'
    | '/inspection/$inspectionId'
    | '/issue/$issueId'
    | '/property/$propertyId'
    | '/request/$requestId'
    | '/thread/$threadId'
    | '/work-order/$workOrderId'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/access'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_tabs/change-password'
    | '/_tabs/edit-profile'
    | '/_tabs/help'
    | '/_tabs/home'
    | '/_tabs/inspection-history'
    | '/_tabs/inspections'
    | '/_tabs/messages'
    | '/_tabs/notifications'
    | '/_tabs/photos'
    | '/_tabs/profile'
    | '/_tabs/properties'
    | '/_tabs/property-new'
    | '/_tabs/reports'
    | '/_tabs/request-new'
    | '/_tabs/requests'
    | '/_tabs/settings'
    | '/_tabs/amenity/$amenityId'
    | '/_tabs/inspection/$inspectionId'
    | '/_tabs/issue/$issueId'
    | '/_tabs/property/$propertyId'
    | '/_tabs/request/$requestId'
    | '/_tabs/thread/$threadId'
    | '/_tabs/work-order/$workOrderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AccessRoute: typeof AccessRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/change-password': {
      id: '/_tabs/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof TabsChangePasswordRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/edit-profile': {
      id: '/_tabs/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof TabsEditProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/help': {
      id: '/_tabs/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof TabsHelpRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/inspection-history': {
      id: '/_tabs/inspection-history'
      path: '/inspection-history'
      fullPath: '/inspection-history'
      preLoaderRoute: typeof TabsInspectionHistoryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/inspections': {
      id: '/_tabs/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof TabsInspectionsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages': {
      id: '/_tabs/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof TabsMessagesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/notifications': {
      id: '/_tabs/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof TabsNotificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/photos': {
      id: '/_tabs/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof TabsPhotosRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/properties': {
      id: '/_tabs/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof TabsPropertiesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/property-new': {
      id: '/_tabs/property-new'
      path: '/property-new'
      fullPath: '/property-new'
      preLoaderRoute: typeof TabsPropertyNewRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reports': {
      id: '/_tabs/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof TabsReportsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/request-new': {
      id: '/_tabs/request-new'
      path: '/request-new'
      fullPath: '/request-new'
      preLoaderRoute: typeof TabsRequestNewRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/requests': {
      id: '/_tabs/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof TabsRequestsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/settings': {
      id: '/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TabsSettingsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/amenity/$amenityId': {
      id: '/_tabs/amenity/$amenityId'
      path: '/amenity/$amenityId'
      fullPath: '/amenity/$amenityId'
      preLoaderRoute: typeof TabsAmenityAmenityIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/inspection/$inspectionId': {
      id: '/_tabs/inspection/$inspectionId'
      path: '/inspection/$inspectionId'
      fullPath: '/inspection/$inspectionId'
      preLoaderRoute: typeof TabsInspectionInspectionIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/issue/$issueId': {
      id: '/_tabs/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/issue/$issueId'
      preLoaderRoute: typeof TabsIssueIssueIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/property/$propertyId': {
      id: '/_tabs/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof TabsPropertyPropertyIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/request/$requestId': {
      id: '/_tabs/request/$requestId'
      path: '/request/$requestId'
      fullPath: '/request/$requestId'
      preLoaderRoute: typeof TabsRequestRequestIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/thread/$threadId': {
      id: '/_tabs/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof TabsThreadThreadIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/work-order/$workOrderId': {
      id: '/_tabs/work-order/$workOrderId'
      path: '/work-order/$workOrderId'
      fullPath: '/work-order/$workOrderId'
      preLoaderRoute: typeof TabsWorkOrderWorkOrderIdRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsChangePasswordRoute: typeof TabsChangePasswordRoute
  TabsEditProfileRoute: typeof TabsEditProfileRoute
  TabsHelpRoute: typeof TabsHelpRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsInspectionHistoryRoute: typeof TabsInspectionHistoryRoute
  TabsInspectionsRoute: typeof TabsInspectionsRoute
  TabsMessagesRoute: typeof TabsMessagesRoute
  TabsNotificationsRoute: typeof TabsNotificationsRoute
  TabsPhotosRoute: typeof TabsPhotosRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsPropertiesRoute: typeof TabsPropertiesRoute
  TabsPropertyNewRoute: typeof TabsPropertyNewRoute
  TabsReportsRoute: typeof TabsReportsRoute
  TabsRequestNewRoute: typeof TabsRequestNewRoute
  TabsRequestsRoute: typeof TabsRequestsRoute
  TabsSettingsRoute: typeof TabsSettingsRoute
  TabsAmenityAmenityIdRoute: typeof TabsAmenityAmenityIdRoute
  TabsInspectionInspectionIdRoute: typeof TabsInspectionInspectionIdRoute
  TabsIssueIssueIdRoute: typeof TabsIssueIssueIdRoute
  TabsPropertyPropertyIdRoute: typeof TabsPropertyPropertyIdRoute
  TabsRequestRequestIdRoute: typeof TabsRequestRequestIdRoute
  TabsThreadThreadIdRoute: typeof TabsThreadThreadIdRoute
  TabsWorkOrderWorkOrderIdRoute: typeof TabsWorkOrderWorkOrderIdRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsChangePasswordRoute: TabsChangePasswordRoute,
  TabsEditProfileRoute: TabsEditProfileRoute,
  TabsHelpRoute: TabsHelpRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsInspectionHistoryRoute: TabsInspectionHistoryRoute,
  TabsInspectionsRoute: TabsInspectionsRoute,
  TabsMessagesRoute: TabsMessagesRoute,
  TabsNotificationsRoute: TabsNotificationsRoute,
  TabsPhotosRoute: TabsPhotosRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsPropertiesRoute: TabsPropertiesRoute,
  TabsPropertyNewRoute: TabsPropertyNewRoute,
  TabsReportsRoute: TabsReportsRoute,
  TabsRequestNewRoute: TabsRequestNewRoute,
  TabsRequestsRoute: TabsRequestsRoute,
  TabsSettingsRoute: TabsSettingsRoute,
  TabsAmenityAmenityIdRoute: TabsAmenityAmenityIdRoute,
  TabsInspectionInspectionIdRoute: TabsInspectionInspectionIdRoute,
  TabsIssueIssueIdRoute: TabsIssueIssueIdRoute,
  TabsPropertyPropertyIdRoute: TabsPropertyPropertyIdRoute,
  TabsRequestRequestIdRoute: TabsRequestRequestIdRoute,
  TabsThreadThreadIdRoute: TabsThreadThreadIdRoute,
  TabsWorkOrderWorkOrderIdRoute: TabsWorkOrderWorkOrderIdRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AccessRoute: AccessRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
